auto: true
pygments: true
permalink: /blog/:year-:month-:day/:title
markdown: maruku

domain: rus.har.mn
#disqus_developer: 1
birthdate: August 9, 1988
disqus_shortname: eatnumber1
github_username: eatnumber1
twitter_username: eatnumber1
google_latitude_id: 4048757213362106746
google_analytics_id: UA-10349264-2
google_plus_id: 112862864127564162879

maruku:
    use_divs: true
    use_tex: true
    png_engine: blahtex
    png_dir: images/latex/
    png_url: /images/latex/

description: The personal website and blog of Russell Harmon
